# Single Docker Image with Multiple Container Profiles
services:
  # Default service - runs all tests
  playwright-tests:
    build: .
    image: playwright-mcp-server:latest
    container_name: playwright-mcp-tests
    environment:
      - NODE_ENV=test
      - HEADLESS=true
      - BASE_URL=https://newsela.com
    volumes:
      - ./artifacts:/app/artifacts
      - ./e2e/reports:/app/e2e/reports
      - ./postman/reports:/app/postman/reports
      - ./playwright-report:/app/playwright-report
      - ./test-results:/app/test-results
    command: npm run test:all

  # Individual Test Containers (same image, different commands)
  smoke:
    image: playwright-mcp-server:latest
    container_name: smoke-tests
    environment:
      - NODE_ENV=test
      - HEADLESS=true
      - BASE_URL=https://newsela.com
    volumes:
      - ./artifacts:/app/artifacts
      - ./e2e/reports:/app/e2e/reports
    command: npm run smoke
    profiles: [smoke]

  functional:
    image: playwright-mcp-server:latest
    container_name: functional-tests
    environment:
      - NODE_ENV=test
      - HEADLESS=true
      - BASE_URL=https://newsela.com
    volumes:
      - ./artifacts:/app/artifacts
      - ./e2e/reports:/app/e2e/reports
    command: npm run functional
    profiles: [functional]

  performance:
    image: playwright-mcp-server:latest
    container_name: performance-tests
    environment:
      - NODE_ENV=test
      - HEADLESS=true
      - BASE_URL=https://newsela.com
    volumes:
      - ./artifacts:/app/artifacts
      - ./e2e/reports:/app/e2e/reports
    command: npm run performance
    profiles: [performance]

  accessibility:
    image: playwright-mcp-server:latest
    container_name: accessibility-tests
    environment:
      - NODE_ENV=test
      - HEADLESS=true
      - BASE_URL=https://newsela.com
    volumes:
      - ./artifacts:/app/artifacts
      - ./e2e/reports:/app/e2e/reports
      - ./playwright-report:/app/playwright-report
      - ./test-results:/app/test-results
    command: npm run test -- --grep accessibility
    profiles: [accessibility]

  security:
    image: playwright-mcp-server:latest
    container_name: security-tests
    environment:
      - NODE_ENV=test
      - HEADLESS=true
      - BASE_URL=https://newsela.com
    volumes:
      - ./artifacts:/app/artifacts
      - ./e2e/reports:/app/e2e/reports
    command: npm run security
    profiles: [security]

  api:
    image: playwright-mcp-server:latest
    container_name: api-tests
    environment:
      - NODE_ENV=test
      - BASE_URL=https://newsela.com
    volumes:
      - ./artifacts:/app/artifacts
      - ./postman/reports:/app/postman/reports
    command: npm run api
    profiles: [api]

  # Test Suites (same image, combined commands)
  suite-content:
    image: playwright-mcp-server:latest
    container_name: content-suite-tests
    environment:
      - NODE_ENV=test
      - HEADLESS=true
      - BASE_URL=https://newsela.com
    volumes:
      - ./artifacts:/app/artifacts
      - ./e2e/reports:/app/e2e/reports
    command: npm run suite:content
    profiles: [suite-content]

  suite-quality:
    image: playwright-mcp-server:latest
    container_name: quality-suite-tests
    environment:
      - NODE_ENV=test
      - HEADLESS=true
      - BASE_URL=https://newsela.com
    volumes:
      - ./artifacts:/app/artifacts
      - ./e2e/reports:/app/e2e/reports
      - ./playwright-report:/app/playwright-report
      - ./test-results:/app/test-results
    command: npm run suite:quality
    profiles: [suite-quality]

  suite-all:
    image: playwright-mcp-server:latest
    container_name: all-suite-tests
    environment:
      - NODE_ENV=test
      - HEADLESS=true
      - BASE_URL=https://newsela.com
    volumes:
      - ./artifacts:/app/artifacts
      - ./e2e/reports:/app/e2e/reports
      - ./postman/reports:/app/postman/reports
      - ./playwright-report:/app/playwright-report
      - ./test-results:/app/test-results
    command: npm run suite:all
    profiles: [suite-all]

networks:
  default:
    name: playwright-mcp-network
